---
dependencies:
  - role: docker-compose
  - role: github
    user_name: root
    user_home: /root
  - role: rsync
  - role: deploy-user
    user_name: root
    user_home: /root
    user_private_key: "{{ deploy_private_key }}"
    user_public_key: "{{ deploy_public_key }}"
