# vi: set ft=yaml :

# Nginx web server.
web:
  image: nginx:1.9
  command: nginx
  links:
    - app
  ports:
    - "3002:80"
  volumes:
    - "/var/lib/probedock-production/nginx/nginx.conf:/etc/nginx/nginx.conf:ro"
    - "/var/lib/probedock-production/app/public:/var/lib/probedock/public"
  restart: always

# Rails application.
app:
  image: "probedock/probedock"
  links:
    - db
    - cache

  volumes:
    - "/var/lib/probedock-production/app/public:/usr/src/app/public"
    - "/var/lib/probedock-production/app/tmp:/usr/src/app/tmp"
  env_file:
    - "/vagrant/.env.development.vagrant"
    - "/vagrant/.env-variable.development.vagrant"
  environment:
    RAILS_ENV: production

# Run a rake task.
# This is meant to be run as a one-off task (with "run" instead of "up").
rake:
  image: "probedock/probedock"
  entrypoint: rake
  command: -T
  links:
    - db
    - cache
  volumes:
    - "/var/lib/probedock-production/app/public:/usr/src/app/public"
    - "/var/lib/probedock-production/app/tmp:/usr/src/app/tmp"
  env_file:
    - "/vagrant/.env.development.vagrant"
    - "/vagrant/.env-variable.development.vagrant"
  environment:
    RAILS_ENV: production

# PostgreSQL database.
db:
  image: postgres:9.4
  volumes:
    - "/var/lib/probedock-production/postgresql/data:/var/lib/postgresql/data"
    - "/var/lib/probedock-production/postgresql/init-scripts:/docker-entrypoint-initdb.d"
  restart: always
  environment:
    POSTGRES_PASSWORD: admin

# Redis in-memory database.
cache:
  image: redis:2.8
  command: redis-server --appendonly yes
  volumes:
    - "/var/lib/probedock-production/redis/data:/data"
  restart: always
