default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see rails configuration guide
  # http://guides.rubyonrails.org/configuring.html#database-pooling
  pool: 5

development:
  <<: *default
  database: rox-center
  host: postgres
  username: postgres

test:
  <<: *default
  database: rox-center-test
  host: postgres
  username: postgres
