
# Used by the API to construct URIs.
protocol: https
host: 'rox.example.com'
# port: 443

# Supported authentication modules: database, ldap
#
# With `database` authentication, the following devise modules
# will be loaded: database_authenticatable, registerable, rememberable, trackable.
#
# With `ldap` authentication, the following devise modules will
# be loaded: ldap_authenticatable, rememberable, trackable.
# LDAP configuration is in the following files: `config/ldap.yml`, `config/initializers/ldap.yml`.
#
# You must choose database or ldap. It is not currently possible to
# switch between the two once users have been registered.
authentication_module: database

# Timezones for the computation of test metrics.
# Metrics such as the number of tests written/run per day depend on the timezone.
# They will be computed for each specified timezone.
# NOTE: only the first specified timezone is used for now.
timezones:
  - UTC
