development:
  protocol: <%= ENV['PROBE_DOCK_APP_PROTOCOL'] %>
  host: <%= ENV['PROBE_DOCK_TEST_APP_HOST'] %>
  port: <%= ENV['PROBE_DOCK_APP_PORT'] %>
  mail_from: "<%= ENV['PROBE_DOCK_APP_MAIL_FROM'] %>"

test:
  protocol: <%= ENV['PROBE_DOCK_TEST_APP_PROTOCOL'] %>
  host: <%= ENV['PROBE_DOCK_TEST_TEST_APP_HOST'] %>
  port: <%= ENV['PROBE_DOCK_TEST_APP_PORT'] %>
  mail_from: "<%= ENV['PROBE_DOCK_TEST_APP_MAIL_FROM'] %>"

production:
  protocol: <%= ENV['PROBE_DOCK_APP_PROTOCOL'] %>
  host: <%= ENV['PROBE_DOCK_TEST_APP_HOST'] %>
  port: <%= ENV['PROBE_DOCK_APP_PORT'] %>
  mail_from: "<%= ENV['PROBE_DOCK_APP_MAIL_FROM'] %>"
