<%
rerun = File.file?('rerun.txt') ? IO.read('rerun.txt') : ""
rerun_opts = rerun.to_s.strip.empty? ? "--format #{ENV['CUCUMBER_FORMAT'] || 'progress'} features" : "--format #{ENV['CUCUMBER_FORMAT'] || 'pretty'} #{rerun}"
std_opts = "--format #{ENV['CUCUMBER_FORMAT'] || 'pretty'} --strict --tags ~@wip"
probedock_opts = "--format ProbeDockCucumber::Formatter --out tmp/probedock/cucumber-ruby/output.txt"
%>
default: <%= std_opts %> <%= probedock_opts %> features
wip: --tags @wip:10 --wip --format pretty <%= probedock_opts %> features
rerun: <%= rerun_opts %> --format rerun --out rerun.txt <%= probedock_opts %> --strict --tags ~@wip
