default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see rails configuration guide
  # http://guides.rubyonrails.org/configuring.html#database-pooling
  pool: 5

development:
  <<: *default
  host: <%= ENV['PROBEDOCK_DATABASE_HOST'] || 'localhost' %>
  database: <%= ENV['PROBEDOCK_DATABASE_NAME'] %>
  <%= ENV['PROBEDOCK_DATABASE_USERNAME'] ? "username: #{ENV['PROBEDOCK_DATABASE_USERNAME']}" : '' %>
  <%= ENV['PROBEDOCK_DATABASE_PASSWORD'] ? "password: #{ENV['PROBEDOCK_DATABASE_PASSWORD']}" : '' %>

test: &test
  <<: *default
  host: <%= ENV['PROBEDOCK_TEST_DATABASE_HOST'] || 'localhost' %>
  database: <%= ENV['PROBEDOCK_TEST_DATABASE_NAME'] %>
  <%= ENV['PROBEDOCK_TEST_DATABASE_USERNAME'] ? "username: #{ENV['PROBEDOCK_TEST_DATABASE_USERNAME']}" : '' %>
  <%= ENV['PROBEDOCK_TEST_DATABASE_PASSWORD'] ? "password: #{ENV['PROBEDOCK_TEST_DATABASE_PASSWORD']}" : '' %>

production:
  <<: *default
  host: <%= ENV['PROBEDOCK_DATABASE_HOST'] %>
  database: <%= ENV['PROBEDOCK_DATABASE_NAME'] %>
  username: <%= ENV['PROBEDOCK_DATABASE_USERNAME'] %>
  password: <%= ENV['PROBEDOCK_DATABASE_PASSWORD'] %>

cucumber:
  <<: *test
