# Be sure to restart your server when you modify this file.

# Secret keys for verifying the integrity of signed cookies and generating user passwords.
# If you change the secret token, all old signed cookies will become invalid!
# Make sure each secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can generate cryptographically secure secret keys with `rake secret`.
development:
  secret_key_base: <%= ENV['PROBEDOCK_SECRET_KEY_BASE'] %>
  jwt_secret: <%= ENV['PROBEDOCK_JWT_SECRET'] %>
  mail_address: <%= ENV['PROBEDOCK_MAIL_ADDRESS'] %>
  mail_port: <%= ENV['PROBEDOCK_MAIL_PORT'] %>
  mail_domain: <%= ENV['PROBEDOCK_MAIL_DOMAIN'] %>
  mail_username: <%= ENV['PROBEDOCK_MAIL_USERNAME'] %>
  mail_password: <%= ENV['PROBEDOCK_MAIL_PASSWORD'] %>
  mail_authentication: <%= ENV['PROBEDOCK_MAIL_AUTHENTICATION'] %>

test:
  secret_key_base: <%= ENV['PROBEDOCK_TEST_SECRET_KEY_BASE'] %>
  jwt_secret: <%= ENV['PROBEDOCK_TEST_JWT_SECRET'] %>

production:
  secret_key_base: <%= ENV['PROBEDOCK_SECRET_KEY_BASE'] %>
  jwt_secret: <%= ENV['PROBEDOCK_JWT_SECRET'] %>
  mail_address: <%= ENV['PROBEDOCK_MAIL_ADDRESS'] %>
  mail_port: <%= ENV['PROBEDOCK_MAIL_PORT'] %>
  mail_username: <%= ENV['PROBEDOCK_MAIL_USERNAME'] %>
  mail_password: <%= ENV['PROBEDOCK_MAIL_PASSWORD'] %>
  mail_authentication: <%= ENV['PROBEDOCK_MAIL_AUTHENTICATION'] %>
