---
- name: check docker compose version
  shell: docker-compose --version|sed 's/[^0-9]*\([0-9]\)/\1/'|sed 's/, build.*//'
  register: result
  failed_when: false
  changed_when: result.rc != 0 or result.stdout != docker_compose_version
- name: install docker compose
  get_url: url=https://github.com/docker/compose/releases/download/{{ docker_compose_version }}/docker-compose-Linux-x86_64 dest=/usr/local/bin/docker-compose mode=0755 force=yes
  when: result|changed
