---
- hosts: all
  remote_user: root
  vars:
    deploy_private_key: "{{ lookup('file', 'deploy_id_rsa') }}"
    deploy_public_key: "{{ lookup('file', 'deploy_id_rsa.pub') }}"
  vars_files:
    - versions.yml
  roles:
    - role: probe-dock
