---
- hosts: all
  sudo: yes
  vars_files:
    - versions.yml
  roles:
    - role: docker-user
      user_name: vagrant
    - role: probe-dock
  tasks:
    - authorized_key: user=root key="{{ lookup('file', public_key_file) }}"
